spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:organization_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-message: ON_PARAM
    include-binding-errors: ON_PARAM
    include-stacktrace: ON_PARAM
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,configprops
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.reythecoder.organization: ${LOGGING_LEVEL_COM_REYTHECODER_ORGANIZATION:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:INFO}
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:INFO}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_HIBERNATE_BINDER:INFO}